# Generated by Django 4.0.4 on 2022-05-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_movie_user_rentals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='in_stock',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='movie',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
