# Generated by Django 4.0.4 on 2022-05-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_in_stock_movie_stock_movie_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='checked',
        ),
    ]
