# Generated by Django 4.0.4 on 2022-05-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_movie_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='user_id',
            new_name='user',
        ),
    ]
